### ISSUE TITLE
Possibility of using `;a;` for α, `;b;` for β?

### ISSUE THREAD

**Issue by davidleejy** [jpmvferreira/espanso-mega-pack#8]
Hi, as the title states, would it be possible to consider _adding_ triggers for the greeks in which the colon symbol (:) is replaced with the semicolon (;)? This way, on english keyboards, greek symbols would require two fewer key presses of the shift key to type – tpying a semicolon doesn't require the shift key unlike the colon.

I would be happy to submit a pull request if you're agreeable.

**Comment by jpmvferreira** [comment]
Hey, a-prior it wouldn't cause any conflicts on my side, and although this is one of those problems where the implementation is easy, I cannot be sure about anybody else.

I remember that somewhere, I issued a request where each package could have a customizable keyword, where the user, not the package developer, would choose the trigger. However, I think that there's clearly way too much going on at Espanso for this to be considered.

That said, and because I like to keep consistent triggers, you can always fork this repository and install it locally, which is rather straightforward, and every time there is a commit on my side (which if you look at the commit history is very rarely) you can add those extra triggers and I highly doubt that a conflict will ever take place.

Hopefully in the future we get to have some of those fancy dynamic user-specified features, but as of right now we have to play with what we have.

**Comment by davidleejy** [comment]
Hey, thanks for the prompt response, and also for maintaining this repository.

> I issued a request where each package could have a customizable keyword, where the user, not the package developer, would choose the trigger.

I, too, think that this would be a good idea.

Since there is indeed merit in keeping the trigger consistent (:) in a single repository, I think we'd both be agreeable on closing this issue 🙂
